# Generated by Django 3.0 on 2019-12-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yelp_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimdate',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='factreview',
            name='cool',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='factreview',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='factreview',
            name='funny',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='factreview',
            name='stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='factreview',
            name='useful',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='factreview',
            unique_together={('id', 'date')},
        ),
    ]
